name: Go
on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
      
    - name: Access Path 
      run: cd ./backend/ride-go
      
    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
